name: first
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_storage:
  get_cli: ^1.8.1
  get: 4.6.5
  intl:
  google_fonts:
  sqflite:
  date_picker_timeline:
  flutter_staggered_animations:
  flutter:
    sdk: flutter
  awesome_notifications:
  persistent_bottom_nav_bar_v2: ^4.2.6
  fancy_bottom_navigation: ^0.3.3
  animated_bottom_navigation_bar: ^1.1.0
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  shared_preferences: ^2.0.15
  json_path: ^0.4.2
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  flutter_animate: ^2.0.1
  page_transition: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
